#!/bin/bash

. ./env

gcc -v
rm -rf build
mkdir build
cd build

# Build SPICE GTK
cd ../spice-gtk
git clean -fdx
cd spice-common && git clean -fdx && cd ..
./autogen.sh
cd ../build
mkdir spice-gtk
cd spice-gtk
../../spice-gtk/configure \
    --prefix=/usr \
    --libdir=/usr/lib/x86_64-linux-gnu \
    --enable-smartcard=yes \
    --with-gtk=3.0 \
    --disable-static \
    --enable-introspection \
    --enable-vala \
    --disable-celt051 \
    --enable-usbredir=yes \
    --enable-polkit=yes \
    --enable-dbus=yes \
    --enable-lz4=yes \
    --enable-python-checks \
    --with-usb-acl-helper-dir=/usr/lib/spice-gtk \
    --disable-gtk-doc
make -j$CPUS
cd ..

# Build SPICE Protocol
cd ../spice-protocol
git clean -fdx
./autogen.sh
cd ../build
mkdir spice-protocol
cd spice-protocol
../../spice-protocol/configure \
    --build=x86_64-linux-gnu \
    --prefix=/usr \
    --includedir=\${prefix}/include \
    --mandir=\${prefix}/share/man \
    --infodir=\${prefix}/share/info \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --disable-silent-rules \
    --libdir=\${prefix}/lib/x86_64-linux-gnu \
    --libexecdir=\${prefix}/lib/x86_64-linux-gnu \
    --disable-maintainer-mode \
    --disable-dependency-tracking
make -j$CPUS
cd ..

# Build SPICE
cd ../spice
git clean -fdx
cd spice-common && git clean -fdx && cd ..
./autogen.sh
cd ../build
mkdir spice
cd spice
../../spice/configure \
    --build=x86_64-linux-gnu \
    --prefix=/usr \
    --includedir=\${prefix}/include \
    --mandir=\${prefix}/share/man \
    --infodir=\${prefix}/share/info \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --disable-silent-rules \
    --libdir=\${prefix}/lib/x86_64-linux-gnu \
    --libexecdir=\${prefix}/lib/x86_64-linux-gnu \
    --disable-maintainer-mode \
    --disable-dependency-tracking \
    --disable-celt051 \
    --disable-silent-rules \
    --enable-smartcard
make -j$CPUS
cd ..

# Build QEMU
mkdir qemu
cd qemu
../../qemu/configure \
    --extra-cflags="-fstack-protector-strong -Wformat -Wdate-time -D_FORTIFY_SOURCE=2 -DCONFIG_QEMU_DATAPATH='\"/usr/share/qemu:/usr/share/seabios:/usr/lib/ipxe/qemu\"' -DVENDOR_UBUNTU $CFLAGS $CPPFLAGS" \
    --extra-ldflags="-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed $LDFLAGS" \
    --prefix=/usr \
    --sysconfdir=/etc \
    --libdir=/usr/lib/x86_64-linux-gnu \
    --libexecdir=/lib/qemu \
    --localstatedir=/var \
    --disable-blobs \
    --with-system-pixman \
    --interp-prefix=/etc/qemu-binfmt/%M \
    --localstatedir=/var \
    --disable-user \
    --enable-system \
    --enable-linux-user \
    --enable-modules \
    --enable-linux-aio \
    --audio-drv-list=pa,alsa,sdl,oss \
    --enable-attr \
    --enable-bluez \
    --enable-brlapi \
    --enable-virtfs \
    --enable-cap-ng \
    --enable-curl \
    --enable-fdt \
    --enable-gnutls \
    --disable-gtk \
    --disable-vte \
    --enable-libiscsi \
    --enable-curses \
    --enable-smartcard \
    --with-system-pixman \
    --enable-rbd \
    --enable-vnc-sasl \
    --enable-seccomp \
    --enable-spice \
    --enable-libusb \
    --enable-usb-redir \
    --enable-xen \
    --enable-xfsctl \
    --enable-vnc \
    --enable-vnc-jpeg \
    --enable-vnc-png \
    --enable-kvm \
    --enable-vhost-net
make -j$CPUS
cd ..

# Build libvirt
cd ../libvirt
git clean -fdx
./autogen.sh
cd ../build
mkdir libvirt
cd libvirt
../../libvirt/configure \
    --build=x86_64-linux-gnu \
    --prefix=/usr \
    --includedir=\${prefix}/include \
    --mandir=\${prefix}/share/man \
    --infodir=\${prefix}/share/info \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --disable-silent-rules \
    --libexecdir=\${prefix}/lib/libvirt \
    --disable-maintainer-mode \
    --disable-dependency-tracking \
    --with-default-editor=sensible-editor \
    --disable-silent-rules \
    --disable-rpath \
    --with-qemu \
    --with-qemu-user=libvirt-qemu \
    --with-qemu-group=kvm \
    --with-openvz \
    --with-avahi \
    --with-sasl \
    --with-yajl \
    --without-ssh2 \
    --with-polkit \
    --with-udev \
    --with-storage-fs \
    --with-storage-dir \
    --with-storage-disk \
    --with-init-script=systemd \
    --with-numactl \
    --with-numad \
    --without-selinux \
    --with-esx \
    --without-phyp \
    --with-capng \
    --with-macvtap \
    --with-network \
    --with-netcf \
    --with-xen \
    --with-libxl \
    --with-vbox \
    --with-lxc \
    --with-dtrace \
    --with-audit \
    --without-hal \
    --without-firewalld \
    --without-attr \
    --with-nss-plugin
make -j$CPUS
cd ..

# Build libvirt-glib
cd ../libvirt-glib
git clean -fdx
./autogen.sh
cd ../build
mkdir libvirt-glib
cd libvirt-glib
../../libvirt-glib/configure \
    --build=x86_64-linux-gnu \
    --prefix=/usr \
    --includedir=\${prefix}/include \
    --mandir=\${prefix}/share/man \
    --infodir=\${prefix}/share/info \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --disable-silent-rules \
    --libdir=\${prefix}/lib/x86_64-linux-gnu \
    --libexecdir=\${prefix}/lib/x86_64-linux-gnu \
    --disable-maintainer-mode \
    --disable-dependency-tracking \
    --enable-introspection \
    --enable-vala \
    --libdir=\${prefix}/lib/x86_64-linux-gnu
make -j$CPUS
cd ..

# Build Virt-viewer
cd ../virt-viewer
git clean -fdx
./autogen.sh
cd ../build
mkdir virt-viewer
cd virt-viewer
../../virt-viewer/configure \
    --build=x86_64-linux-gnu \
    --prefix=/usr \
    --includedir=\${prefix}/include \
    --mandir=\${prefix}/share/man \
    --infodir=\${prefix}/share/info \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --disable-silent-rules \
    --libdir=\${prefix}/lib/x86_64-linux-gnu \
    --libexecdir=\${prefix}/lib/x86_64-linux-gnu \
    --disable-maintainer-mode \
    --disable-dependency-tracking \
    --disable-update-mimedb \
    --with-gtk=3.0 \
    --with-spice-gtk
make -j$CPUS
cd ..
